num_nodes_shared: [64]
num_nodes_indiv: [128]
batch_norm: true
verbose: false
dropout: 0.1
alpha: 0.8
sigma: 0.1
batch_size: 32
lr: 0.0005
weight_decay: 0.01
eta_multiplier: 1
epochs: 1000
early_stop: true
patience: 10