num_nodes_shared: [32]
num_nodes_indiv: [64]
batch_norm: true
verbose: false
dropout: 0.5
alpha: 0
sigma: 0.1
batch_size: 32
lr: 0.0001
weight_decay: 0.1
eta_multiplier: 1
epochs: 1000
early_stop: true
patience: 10