num_nodes_shared: [16]
num_nodes_indiv: [64]
batch_norm: true
verbose: false
dropout: 0.25
alpha: 0.4
sigma: 0.05
batch_size: 32
lr: 0.005
weight_decay: 0
eta_multiplier: 1
epochs: 1000
early_stop: true
patience: 10