# deephit-comp
num_nodes_shared: [64, 64]
num_nodes_indiv: [32]
batch_norm: True
verbose: False
dropout: 0.1
alpha: 0.2
sigma: 0.1
batch_size: 32
lr: 0.01
weight_decay: 0.01
eta_multiplier: 0.8
epochs: 5
early_stop: True
patience: 10