num_nodes_shared: [32]
num_nodes_indiv: [32]
batch_norm: true
verbose: false
dropout: 0.25
alpha: 0.2
sigma: 0.1
batch_size: 32
lr: 0.001
weight_decay: 0.01
eta_multiplier: 0.8
epochs: 1000
early_stop: true
patience: 10