# Model
theta_layer_size: [50]
layer_size_fine_bins:
- [100, 10]
lr: 0.001
reg_constant: 0.01
n_batches: 5
batch_size: 32
backward_c_optim: false
hierarchical_loss: true
alpha: 0.001
sigma: 5
use_theta: true
use_deephit: false
n_extra_bins: 1
verbose: false

# Data
num_events: 5
num_bins: 56
terminal_events: []
discrete: False
event_ranks: {0: [2, 3, 4], 1: [2, 3, 4], 2: [3, 4], 3: [], 4: []} #0 Rec, 1 AE, 2 AE & Rec, 3 Relpase, 4 Death
event_groups: {
                0: [0, 1],
                1: [2, 3, 4],
                2: [3, 4],
                3: [],
                4: [],                
              }
min_time: 1
max_time: 56
min_epoch: 1
max_epoch: 1000