# Model
theta_layer_size: [200]
layer_size_fine_bins:
- [150, 10]
lr: 0.001
reg_constant: 0.1
n_batches: 10
batch_size: 32
backward_c_optim: false
hierarchical_loss: true
alpha: 0
sigma: 20
use_theta: true
use_deephit: false
n_extra_bins: 1
verbose: false

# Data
num_events: 3
num_bins: 115
terminal_events: [0]
discrete: False
event_ranks: {0: [1], 1: [0], 2: [0]}
event_groups: {0: [0, 1, 2]}
min_time: 1
max_time: 115
min_epoch: 1
max_epoch: 1000