num_events: 3
num_bins: 15
terminal_events: []
discrete: true
event_ranks: {0: [], 1: [], 2: []}
event_groups: {0: [0, 1, 2], 1: [0, 1, 2], 2: [0, 1, 2]}
min_time: 0
max_time: 120
min_epoch: 1
max_epoch: 100