num_events: 4
num_bins: 56
terminal_events: []
discrete: False
event_ranks: {0: [1], 1: [], 2: [], 3: []}
event_groups: {
                0: [],
                1: [],
                2: [],
                3: [],
              }
min_time: 1
max_time: 56
min_epoch: 1
max_epoch: 1000