# survtrace
num_event: 2
num_hidden_layers: 2
hidden_size: 16
intermediate_size: 64
num_attention_heads: 2
initializer_range: 0.001
batch_size: 32
weight_decay: 0
learning_rate: 0.0001
epochs: 100
early_stop_patience: 5
hidden_dropout_prob: 0
seed: 0
hidden_act: gelu
attention_probs_dropout_prob: 0.1
layer_norm_eps: 1000000000000
checkpoint: ./checkpoints/survtrace.pt
max_position_embeddings: 512
chunk_size_feed_forward: 0
output_attentions': False
output_hidden_states': False
tie_word_embeddings': True
pruned_heads': {}