# Single event
se_alpha_e1: 18
se_alpha_e2: 17
se_gamma_e1: 3
se_gamma_e2: 3
se_n_events: 2
se_n_samples: 20000
se_n_features: 10

# Competing risks
cr_alpha_e1: 18
cr_alpha_e2: 17
cr_alpha_e3: 16
cr_gamma_e1: 3
cr_gamma_e2: 3
cr_gamma_e3: 3
cr_n_events: 3
cr_n_samples: 10000
cr_n_features: 10

# Multi event
me_alpha_e1: 18
me_alpha_e2: 17
me_alpha_e3: 16
me_gamma_e1: 3
me_gamma_e2: 3
me_gamma_e3: 3
me_n_events: 3
me_n_samples: 10000
me_n_features: 10
